source 'https://rubygems.org'
ruby '2.5.1'
gem 'aws-sdk-s3'
gem 'byebug'
gem 'dotenv'
gem 'pg'
gem 'rake'
gem 'rspec'
gem 'rufus-scheduler'
gem 'shotgun'
gem 'sinatra', '>= 2.0.2'
gem 'sinatra-activerecord'
gem 'puma'
group :test do
  gem 'capybara'
  gem 'codecov', require: false
  gem 'database_cleaner'
  gem 'factory_bot'
  gem 'launchy'
  gem 'rack-test'
end
